# Generated by Django 4.2.15 on 2024-08-21 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_rename_entity_name_reference_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='drive_axle_model',
            field=models.ForeignKey(limit_choices_to={'category': 'Модель ведущего моста'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='car_drive_axle_models', to='cars.reference'),
        ),
        migrations.AlterField(
            model_name='car',
            name='engine_model',
            field=models.ForeignKey(limit_choices_to={'category': 'Модель двигателя'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='car_engine_models', to='cars.reference'),
        ),
        migrations.AlterField(
            model_name='car',
            name='steering_axle_model',
            field=models.ForeignKey(limit_choices_to={'category': 'Модель управляемого моста'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='car_steering_axle_models', to='cars.reference'),
        ),
        migrations.AlterField(
            model_name='car',
            name='tech_model',
            field=models.ForeignKey(limit_choices_to={'category': 'Модель техники'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='car_tech_models', to='cars.reference'),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission_model',
            field=models.ForeignKey(limit_choices_to={'category': 'Модель трансмиссии'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='car_transmission_models', to='cars.reference'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='failure_node',
            field=models.ForeignKey(limit_choices_to={'category': 'Узел отказа'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='failure_nodes', to='cars.reference'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='recovery_method',
            field=models.ForeignKey(limit_choices_to={'category': '\tСпособ восстановления'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recovery_methods', to='cars.reference'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='maintenance_organization',
            field=models.ForeignKey(limit_choices_to={'category': 'Организация, проводившая ТО'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_organizations', to='cars.reference'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='maintenance_type',
            field=models.ForeignKey(limit_choices_to={'category': 'Вид ТО'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_types', to='cars.reference'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='category',
            field=models.CharField(choices=[('Модель техники', 'Модель техники'), ('Модель двигателя', 'Модель двигателя'), ('Модель трансмиссии', 'Модель трансмиссии'), ('Модель ведущего моста', 'Модель ведущего моста'), ('Модель управляемого моста', 'Модель управляемого моста'), ('Вид ТО', 'Вид ТО'), ('Организация, проводившая ТО', 'Организация, проводившая ТО'), ('Узел отказа', 'Узел отказа'), ('Способ восстановления', 'Способ восстановления')], max_length=100),
        ),
    ]
