# Generated by Django 4.2.15 on 2024-09-01 17:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cars', '0003_alter_car_drive_axle_model_alter_car_engine_model_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'permissions': [('can_add_car', 'Can add car'), ('can_change_car', 'Can change car')]},
        ),
        migrations.AlterModelOptions(
            name='complaint',
            options={'permissions': [('can_add_complaint', 'Can add complaint'), ('can_change_complaint', 'Can change complaint')]},
        ),
        migrations.AlterModelOptions(
            name='maintenance',
            options={'permissions': [('can_add_maintenance', 'Can add maintenance'), ('can_change_maintenance', 'Can change maintenance')]},
        ),
        migrations.AlterField(
            model_name='car',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_cars', to=settings.AUTH_USER_MODEL, verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='car',
            name='consignee',
            field=models.CharField(max_length=255, verbose_name='Грузополучатель (конечный потребитель)'),
        ),
        migrations.AlterField(
            model_name='car',
            name='delivery_address',
            field=models.CharField(max_length=255, verbose_name='Адрес поставки (эксплуатации)'),
        ),
        migrations.AlterField(
            model_name='car',
            name='drive_axle_model',
            field=models.ForeignKey(limit_choices_to={'category': 'Модель ведущего моста'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='car_drive_axle_models', to='cars.reference', verbose_name='Модель ведущего моста'),
        ),
        migrations.AlterField(
            model_name='car',
            name='drive_axle_number',
            field=models.CharField(max_length=255, verbose_name='Зав. № ведущего моста'),
        ),
        migrations.AlterField(
            model_name='car',
            name='engine_model',
            field=models.ForeignKey(limit_choices_to={'category': 'Модель двигателя'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='car_engine_models', to='cars.reference', verbose_name='Модель двигателя'),
        ),
        migrations.AlterField(
            model_name='car',
            name='engine_number',
            field=models.CharField(max_length=255, verbose_name='Зав. № двигателя'),
        ),
        migrations.AlterField(
            model_name='car',
            name='equipment',
            field=models.TextField(verbose_name='Комплектация (доп. опции)'),
        ),
        migrations.AlterField(
            model_name='car',
            name='factory_number',
            field=models.CharField(max_length=255, unique=True, verbose_name='Зав. № машины'),
        ),
        migrations.AlterField(
            model_name='car',
            name='service_company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_company_cars', to=settings.AUTH_USER_MODEL, verbose_name='Сервисная компания'),
        ),
        migrations.AlterField(
            model_name='car',
            name='shipping_date',
            field=models.DateField(verbose_name='Дата отгрузки с завода'),
        ),
        migrations.AlterField(
            model_name='car',
            name='steering_axle_model',
            field=models.ForeignKey(limit_choices_to={'category': 'Модель управляемого моста'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='car_steering_axle_models', to='cars.reference', verbose_name='Модель управляемого моста'),
        ),
        migrations.AlterField(
            model_name='car',
            name='steering_axle_number',
            field=models.CharField(max_length=255, verbose_name='Зав. № управляемого моста'),
        ),
        migrations.AlterField(
            model_name='car',
            name='supply_contract',
            field=models.CharField(max_length=255, verbose_name='Договор поставки №, дата'),
        ),
        migrations.AlterField(
            model_name='car',
            name='tech_model',
            field=models.ForeignKey(limit_choices_to={'category': 'Модель техники'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='car_tech_models', to='cars.reference', verbose_name='Модель техники'),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission_model',
            field=models.ForeignKey(limit_choices_to={'category': 'Модель трансмиссии'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='car_transmission_models', to='cars.reference', verbose_name='Модель трансмиссии'),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission_number',
            field=models.CharField(max_length=255, verbose_name='Зав. № трансмиссии'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='cars.car', verbose_name='Машина'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='downtime',
            field=models.FloatField(verbose_name='Время простоя техники'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='failure_date',
            field=models.DateField(verbose_name='Дата отказа'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='failure_description',
            field=models.TextField(verbose_name='Описание отказа'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='failure_node',
            field=models.ForeignKey(limit_choices_to={'category': 'Узел отказа'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='failure_nodes', to='cars.reference', verbose_name='Узел отказа'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='operating_time',
            field=models.FloatField(verbose_name='Наработка, м/час'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='parts_used',
            field=models.TextField(verbose_name='Используемые запасные части'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='recovery_date',
            field=models.DateField(verbose_name='Дата восстановления'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='recovery_method',
            field=models.ForeignKey(limit_choices_to={'category': 'Способ восстановления'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recovery_methods', to='cars.reference', verbose_name='Способ восстановления'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='service_company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaint_service_companies', to=settings.AUTH_USER_MODEL, verbose_name='Сервисная компания'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenances', to='cars.car', verbose_name='Машина'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='date',
            field=models.DateField(verbose_name='Дата проведения ТО'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='maintenance_organization',
            field=models.ForeignKey(limit_choices_to={'category': 'Организация, проводившая ТО'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_organizations', to='cars.reference', verbose_name='Организация, проводившая ТО'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='maintenance_type',
            field=models.ForeignKey(limit_choices_to={'category': 'Вид ТО'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_types', to='cars.reference', verbose_name='Вид ТО'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='operating_time',
            field=models.FloatField(verbose_name='Наработка, м/час'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='order_date',
            field=models.DateField(verbose_name='Дата заказ-наряда'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='order_number',
            field=models.CharField(max_length=255, verbose_name='№ заказ-наряда'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='service_company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_service_companies', to=settings.AUTH_USER_MODEL, verbose_name='Сервисная компания'),
        ),
    ]
