# Generated by Django 4.2.15 on 2024-09-01 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_alter_car_options_alter_complaint_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={},
        ),
        migrations.AlterModelOptions(
            name='complaint',
            options={},
        ),
        migrations.AlterModelOptions(
            name='maintenance',
            options={},
        ),
    ]
